# Generated by Django 3.1.7 on 2021-04-28 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filesharing.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filesharing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='isprivate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=filesharing.models.user_directory_path),
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedfolder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filesharing.folder')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filesharing.folder'),
        ),
    ]
